version: '3.8'

services:
  base_image:
    build:
      context: ./base_image
    image: base_image:latest
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server=localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  async_worker:
    build: ./async_worker
    container_name: async_worker
    depends_on:
      kafka:
        condition: service_healthy
      base_image:
        condition: service_started
    environment:
      BROKER_URL: "kafka://kafka:9092"
    networks:
      - kafka-network

  api_rest:
    build: ./api_rest
    container_name: api_rest
    depends_on:
      kafka:
        condition: service_healthy
      base_image:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
